/**
   This file borrows heavily from the grpc library. The LICENSE for
   that library is included because of the high degree of similarity:

   Copyright 2015, Google Inc.
   All rights reserved.

   Redistribution and use in source and binary forms, with or without
   modification, are permitted provided that the following conditions are
   met:

   * Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.
   * Redistributions in binary form must reproduce the above
   copyright notice, this list of conditions and the following disclaimer
   in the documentation and/or other materials provided with the
   distribution.
   * Neither the name of Google Inc. nor the names of its
   contributors may be used to endorse or promote products derived from
   this software without specific prior written permission.

   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
   "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
   LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
   A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
   OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
   SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
   LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
   DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
   THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
   OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**/

#include "nodejs_generator.h"

#include <dotdashpay/api/common/protobuf/api_common.pb.h>
#include <google/protobuf/descriptor.pb.h>
#include <google/protobuf/io/printer.h>
#include <google/protobuf/io/zero_copy_stream_impl.h>
#include <map>
#include <set>
#include <sstream>
#include <string>
#include <vector>

using namespace ddprpc_generator;

using std::map;
using std::set;
using std::string;
using std::vector;

namespace ddprpc_nodejs_generator {
namespace {

const char* GetLodashChecker(const google::protobuf::FieldDescriptor* descriptor) {
  google::protobuf::FieldDescriptor::Type type = descriptor->type();
  switch (type) {
    case google::protobuf::FieldDescriptor::TYPE_INT32:
    case google::protobuf::FieldDescriptor::TYPE_UINT32:
      return "_.isInteger";
    case google::protobuf::FieldDescriptor::TYPE_INT64:
    case google::protobuf::FieldDescriptor::TYPE_UINT64:
      return nullptr;
    case google::protobuf::FieldDescriptor::TYPE_FLOAT:
    case google::protobuf::FieldDescriptor::TYPE_DOUBLE:
      return "_.isNumber";
    case google::protobuf::FieldDescriptor::TYPE_BOOL:
      return "_.isBoolean";
    case google::protobuf::FieldDescriptor::TYPE_STRING:
      return "_.isString";
    case google::protobuf::FieldDescriptor::TYPE_MESSAGE:
      return "_.isObject";
    case google::protobuf::FieldDescriptor::TYPE_ENUM:
    default:
      return nullptr;
  }

  return nullptr;
}

string GetFieldCheckingStatements(const string& field_name, const google::protobuf::FieldDescriptor* descriptor) {
  if (!descriptor->is_required()) {
    return "false";
  }

  const char* checker = GetLodashChecker(descriptor);
  const string base_checking = "_.isUndefined(" + field_name + ") || _.isNull(" + field_name + ")";

  if (checker != nullptr) {
    return base_checking + " || !" + string(checker) + "(" + field_name + ")";
  } else {
    return base_checking;
  }
}

}  // namespace

string GetPrologue(const google::protobuf::FileDescriptor *file, const Parameters &params) {
  string output;
  {
    // Scope the output stream so it closes and finalizes output to the string.
    google::protobuf::io::StringOutputStream output_stream(&output);
    google::protobuf::io::Printer printer(&output_stream, '$');
    map<string, string> vars;

    vars["filename"] = file->name();

    vars["major_version"] = std::to_string(file->options().GetExtension(dotdashpay::api::common::api_major_version));
    vars["minor_version"] = std::to_string(file->options().GetExtension(dotdashpay::api::common::api_minor_version));

    printer.Print(vars, "//\n");
    printer.Print(vars, "//  Automatically generated from $filename$\n");
    printer.Print(vars, "//  DO NOT EDIT THIS FILE DIRECTLY.\n");
    printer.Print(vars, "//\n");
    printer.Print(vars, "\n");
    printer.Print(vars, "const DDP_API_MAJOR_VERSION = $major_version$;\n");
    printer.Print(vars, "const DDP_API_MINOR_VERSION = $minor_version$;\n");
    printer.Print(vars, "\n");
  }
  return output;
}

string GetServiceImplementation(const google::protobuf::ServiceDescriptor* service,
                                const Parameters &params) {
  string output;
  {
    // Scope the output stream so it closes and finalizes output to the string.
    google::protobuf::io::StringOutputStream output_stream(&output);
    google::protobuf::io::Printer printer(&output_stream, '$');
    map<string, string> vars;

    vars["ServiceCanonical"] = service->name();
    vars["Service"] = LowercaseFirstLetter(service->name());

    for (int i = 0; i < service->method_count(); ++i) {
      const google::protobuf::MethodDescriptor* method = service->method(i);

      vars["Method"] = LowercaseFirstLetter(method->name());
      vars["MethodCanonical"] = method->name();
      vars["MethodArgs"] = ddprpc_nodejs_generator::GetClassPrefix() + method->input_type()->name();
      vars["MethodArgsFull"] = method->input_type()->full_name();
      vars["CompletionResponseName"] = GetCompletionResponse(method);
      vars["CompletionResponseClass"] = ddprpc_nodejs_generator::GetClassPrefix() + GetCompletionResponse(method);
      const vector<string> update_responses = GetUpdateResponses(method);

      const google::protobuf::Descriptor* request = FindMessageByName(service->file(), vars["MethodArgs"]);

      printer.Print(vars, "module.exports.$Method$ = function($MethodArgs$) {\n");
      printer.Indent();
      for (int j = 0; j < request->field_count(); ++j) {
        const google::protobuf::FieldDescriptor* field = request->field(j);

        vars["FieldName"] = field->name();
        vars["Checker"] = GetFieldCheckingStatements(vars["MethodArgs"] + "." + field->name(), field);

        if (vars["Checker"] != "false") {
          printer.Print(vars, "if ($Checker$) {\n");
          printer.Indent();
          printer.Print(vars, "throw Error(\"in `$Method$`, `$FieldName$` has incorrect type: ");
          printer.Print(vars, "\" + typeof($MethodArgs$.$FieldName$));\n");
          printer.Outdent();
          printer.Print(vars, "}\n\n");
        }
      }

      printer.Print(vars, "var builder = requestProtobufs.getProtobufBuilder();\n");

      printer.Print(vars, "// TODO(cjrd) check the data\n");
      printer.Print(vars, "return Server.createRequestThenSend(\"$MethodCanonical$\", {\n");
      printer.Indent();
      for (int j = 0; j < request->field_count(); ++j) {
        const google::protobuf::FieldDescriptor* field = request->field(j);

        vars["FieldName"] = field->name();
        printer.Print(vars, "$FieldName$: $MethodArgs$.$FieldName$");
        if (field->has_default_value()) {
          printer.Print(vars, " || builder.$MethodArgsFull$.$$type.getChild(\"$FieldName$\").defaultValue");
        }

        if (j < request->field_count() - 1) {
          printer.Print(vars, ",\n");
        } else {
          printer.Print(vars, "\n");
        }
      }
      printer.Outdent();
      printer.Print(vars, "});\n");

      printer.Outdent();
      printer.Print(vars, "};\n\n");
    }
  }
  return output;
}

string GetSourceIncludes(const google::protobuf::ServiceDescriptor* service, const Parameters &params) {
  string output;
  {
    // Scope the output stream so it closes and finalizes output to the string.
    google::protobuf::io::StringOutputStream output_stream(&output);
    google::protobuf::io::Printer printer(&output_stream, '$');
    map<string, string> vars;

    printer.Print(vars, "var _ = require(\"lodash\");\n");
    printer.Print(vars, "var requestProtobufs = require(\"./internal/request-protobufs\");\n");
    printer.Print(vars, "var Server = require(\"./internal/server\");\n");
    printer.Print(vars, "\n");
  }
  return output;
}

}  // namespace ddprpc_nodejs_generator
