/**
   This file borrows heavily from the grpc library. The LICENSE for
   that library is included because of the high degree of similarity:

   Copyright 2015, Google Inc.
   All rights reserved.

   Redistribution and use in source and binary forms, with or without
   modification, are permitted provided that the following conditions are
   met:

   * Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.
   * Redistributions in binary form must reproduce the above
   copyright notice, this list of conditions and the following disclaimer
   in the documentation and/or other materials provided with the
   distribution.
   * Neither the name of Google Inc. nor the names of its
   contributors may be used to endorse or promote products derived from
   this software without specific prior written permission.

   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
   "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
   LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
   A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
   OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
   SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
   LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
   DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
   THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
   OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**/

#include "objc_generator.h"

#include <dotdashpay/api/common/protobuf/api_common.pb.h>
#include <google/protobuf/compiler/objectivec/objectivec_helpers.h>
#include <google/protobuf/descriptor.pb.h>
#include <google/protobuf/io/printer.h>
#include <google/protobuf/io/zero_copy_stream_impl.h>
#include <map>
#include <set>
#include <sstream>
#include <string>
#include <vector>

using ::google::protobuf::compiler::objectivec::ClassName;
using std::map;
using std::set;
using std::string;
using std::vector;

namespace ddprpc_objc_generator {
namespace {

template <class T>
string as_string(T x) {
  std::ostringstream out;
  out << x;
  return out.str();
}

string FilenameIdentifier(const string &filename) {
  string result;
  for (unsigned i = 0; i < filename.size(); i++) {
    char c = filename[i];
    if (isalnum(c)) {
      result.push_back(c);
    } else {
      static char hex[] = "0123456789abcdef";
      result.push_back('_');
      result.push_back(hex[(c >> 4) & 0xf]);
      result.push_back(hex[c & 0xf]);
    }
  }
  return result;
}

string GetClassPrefix() {
  return "";
}

}  // namespace

string GetPrologue(const google::protobuf::FileDescriptor *file,
                   const Parameters &params, const bool& is_header) {
  string output;
  {
    // Scope the output stream so it closes and finalizes output to the string.
    google::protobuf::io::StringOutputStream output_stream(&output);
    google::protobuf::io::Printer printer(&output_stream, '$');
    map<string, string> vars;

    vars["filename"] = file->name();
    vars["filename_identifier"] = FilenameIdentifier(file->name());
    vars["filename_base"] = ddprpc_generator::StripProto(file->name());

    vars["major_version"] = std::to_string(file->options().GetExtension(dotdashpay::api::common::api_major_version));
    vars["minor_version"] = std::to_string(file->options().GetExtension(dotdashpay::api::common::api_minor_version));

    printer.Print(vars, "//\n");
    printer.Print(vars, "//  Automatically generated from $filename$\n");
    printer.Print(vars, "//  DO NOT EDIT THIS FILE DIRECTLY.\n");
    printer.Print(vars, "//\n");
    printer.Print(vars, "\n");
    if (is_header) {
      printer.Print(vars, "#define DDP_API_MAJOR_VERSION $major_version$\n");
      printer.Print(vars, "#define DDP_API_MINOR_VERSION $minor_version$\n");
      printer.Print(vars, "\n");
    }
  }
  return output;
}

void PrintSimulatorMethods(google::protobuf::io::Printer *printer,
                           const google::protobuf::FileDescriptor* file,
                           map<string, string> *vars,
                           const bool& is_header) {
  const set<string> responses = ddprpc_generator::GetUniqueResponses(file);

  for (set<string>::iterator it = responses.begin(); it != responses.end(); ++it) {
    (*vars)["ResponseName"] = *it;
    printer->Print(*vars, "+ (void) setResponse$ResponseName$:($ResponseName$*)response");
    if (is_header) {
      printer->Print(*vars, ";\n\n");
    } else {
      printer->Print("{\n");
      printer->Indent();
      printer->Print(*vars, "[SimulatorHelper setResponse:@\"$ResponseName$\" withResponseData:response];\n");
      printer->Outdent();
      printer->Print(*vars, "}\n\n");
    }
  }
}

string GetSimulatorHeader(const google::protobuf::FileDescriptor* file,
                          const Parameters &params) {
  string output;
  {
    // Scope the output stream so it closes and finalizes output to the string.
    google::protobuf::io::StringOutputStream output_stream(&output);
    google::protobuf::io::Printer printer(&output_stream, '$');
    map<string, string> vars;

    printer.Print(vars, "#import <Foundation/Foundation.h>\n\n");

    const set<string> responses = ddprpc_generator::GetUniqueResponses(file);
    for (set<string>::iterator it = responses.begin(); it != responses.end(); ++it) {
      vars["ResponseName"] = *it;
      printer.Print(vars, "@class $ResponseName$;\n");
    }
    printer.Print(vars, "\n");

    printer.Print(vars, "@interface DDPSimulatorManager : NSObject\n\n");

    printer.Print(vars, "+ (NSArray*) getResponsesForRequest:(NSString*)request;\n\n");
    PrintSimulatorMethods(&printer, file, &vars, true);
    printer.Print(vars, "@end\n");
  }

  return output;
}

std::string GetSimulatorSource(const google::protobuf::FileDescriptor* file, const Parameters &params) {
  string output;
  {
    // Scope the output stream so it closes and finalizes output to the string.
    google::protobuf::io::StringOutputStream output_stream(&output);
    google::protobuf::io::Printer printer(&output_stream, '$');
    map<string, string> vars;

    printer.Print(vars, "#import \"DDPSimulatorManager.h\"\n\n");
    printer.Print(vars, "#import \"SimulatorHelper.h\"\n\n");

    printer.Print(vars, "@implementation DDPSimulatorManager\n\n");

    printer.Print(vars, "+ (NSArray*) getResponsesForRequest:(NSString*)request {\n");
    printer.Indent();
    for (int i = 0; i < file->service_count(); ++i) {
      const google::protobuf::ServiceDescriptor* service = file->service(i);
      for (int j = 0; j < service->method_count(); ++j) {
        const google::protobuf::MethodDescriptor* method = service->method(j);
        vars["MethodName"] = method->name();
        printer.Print(vars, "if ([request isEqualToString:@\"$MethodName$\"]) {\n");
        printer.Indent();

        printer.Print(vars, "return @[");

        vector<string> responses = ddprpc_generator::GetUpdateResponses(method);
        for (int k = 0; k < responses.size(); ++k) {
          vars["UpdateResponseName"] = responses[k];
          printer.Print(vars, "@\"$UpdateResponseName$\", ");
        }
        vars["CompletionResponseName"] = ddprpc_generator::GetCompletionResponse(method);
        printer.Print(vars, "@\"$CompletionResponseName$\"");

        printer.Print(vars, "];\n");
        printer.Outdent();
        printer.Print(vars, "}\n\n");
      }
    }

    printer.Print(vars, "return nil;\n");
    printer.Outdent();
    printer.Print(vars, "}\n\n");

    PrintSimulatorMethods(&printer, file, &vars, false);
    printer.Print(vars, "@end\n");
  }

  return output;
}

string GetHeaderIncludes(const google::protobuf::ServiceDescriptor* service,
                         const Parameters &params) {
  string output;
  {
    // Scope the output stream so it closes and finalizes output to the string.
    google::protobuf::io::StringOutputStream output_stream(&output);
    google::protobuf::io::Printer printer(&output_stream, '$');
    map<string, string> vars;

    vars["ServiceMessagesIncludeFile"] = service->name() + ".pbobjc.h";
    printer.Print(vars, "#import <Foundation/Foundation.h>\n\n");
    printer.Print(vars, "#import \"DDPCallback.h\"\n\n");

    // Forward decl all of the Args and responses classes.
    set<string> classes = ddprpc_generator::GetUniqueResponses(service);
    for (int i = 0; i < service->method_count(); ++i) {
      classes.insert(ddprpc_objc_generator::GetClassPrefix() + service->method(i)->name() + "Args");
    }

    for (set<string>::iterator it = classes.begin(); it != classes.end(); ++it) {
      vars["ClassName"] = *it;
      printer.Print(vars, "@class $ClassName$;\n");
    }
    printer.Print(vars, "\n");
  }
  return output;
}

void PrintMethodSuffix(google::protobuf::io::Printer *printer, const bool& is_declaration) {
  if (is_declaration) {
    printer->Print(";\n\n");
  } else {
    printer->Print(" {\n");
  }
}

void PrintHeaderClientMethodInterfaces(
    google::protobuf::io::Printer *printer,
    const google::protobuf::MethodDescriptor *method,
    map<string, string> *vars,
    const bool& is_declaration) {
  (*vars)["Method"] = ddprpc_generator::LowercaseFirstLetter(method->name());
  (*vars)["MethodArgs"] = ddprpc_objc_generator::GetClassPrefix() + method->name() + "Args";
  (*vars)["Request"] = ClassName(method->input_type());
  (*vars)["Response"] = ClassName(method->output_type());
  (*vars)["CompletionResponseName"] = ddprpc_generator::GetCompletionResponse(method);
  (*vars)["CompletionResponseClass"]
      = ddprpc_objc_generator::GetClassPrefix() + ddprpc_generator::GetCompletionResponse(method);
  const vector<string> update_responses = ddprpc_generator::GetUpdateResponses(method);

  printer->Print(
      *vars,
      "- (void) $Method$:($MethodArgs$*)args "
      "on$CompletionResponseName$:(void(^)(NSError*, $CompletionResponseClass$*))completionCallback");
  PrintMethodSuffix(printer, is_declaration);

  if (update_responses.size() > 0) {
    if (!is_declaration) {
      printer->Indent();
      printer->Print(*vars, "[self $Method$:args");
      for (int i = 0; i < update_responses.size(); ++i) {
        (*vars)["UpdateResponse"] = update_responses[i];
        printer->Print(*vars, " on$UpdateResponse$:nil");
      }
      printer->Print(*vars, " on$CompletionResponseName$:completionCallback];\n");
      printer->Outdent();
      printer->Print(*vars, "}\n\n");
    }

    printer->Print(*vars, "- (void) $Method$:($MethodArgs$*)args");
    for (int i = 0; i < update_responses.size(); ++i) {
      (*vars)["UpdateResponseName"] = update_responses[i];
      (*vars)["UpdateResponseClass"] = ddprpc_objc_generator::GetClassPrefix() + (update_responses[i]);
      printer->Print(
          *vars, " on$UpdateResponseName$:(void(^)(NSError*, $UpdateResponseClass$*))$UpdateResponseClass$callback");
    }
    printer->Print(
        *vars," on$CompletionResponseName$:(void(^)(NSError*, $CompletionResponseClass$*))completionCallback");
    PrintMethodSuffix(printer, is_declaration);
  }
}

string GetHeaderService(const google::protobuf::ServiceDescriptor* service,
                        const Parameters &params) {
  string output;
  {
    // Scope the output stream so it closes and finalizes output to the string.
    google::protobuf::io::StringOutputStream output_stream(&output);
    google::protobuf::io::Printer printer(&output_stream, '$');
    map<string, string> vars;

    vars["Service"] = "DDP" + service->name();
    printer.Print(vars, "@interface $Service$ : NSObject\n\n");

    for (int i = 0; i < service->method_count(); ++i) {
      PrintHeaderClientMethodInterfaces(&printer, service->method(i), &vars, true);
    }

    printer.Print(vars, "\n");
    printer.Print(vars, "@end");
  }
  return output;
}


void PrintServiceMethodImplementation(google::protobuf::io::Printer *printer,
                                      const google::protobuf::MethodDescriptor *method,
                                      map<string, string> *vars) {
  (*vars)["ServiceName"] = "DDP" + method->service()->name();
  (*vars)["Method"] = ddprpc_generator::LowercaseFirstLetter(method->name());
  (*vars)["MethodName"] = method->name();
  (*vars)["CompletionResponse"] = ddprpc_generator::GetCompletionResponse(method);
  const vector<string> update_responses = ddprpc_generator::GetUpdateResponses(method);

  for (int i = 0; i < update_responses.size(); ++i) {
    (*vars)["UpdateResponse"] = update_responses[i];
    printer->Print(*vars, "[SignalManager clear:@\"$UpdateResponse$\"];\n");
  }
  printer->Print(*vars, "[SignalManager clear:@\"$CompletionResponse$\"];\n");
  printer->Print(
      *vars, "[[Bridge getInstance] sendRequest:@\"$MethodName$\" withArgs:args completionBlock:^(BOOL sent) {\n");

  printer->Indent();
  printer->Print(*vars, "VLOG(2, @\"$ServiceName$::$MethodName$: %d\", sent);\n");
  printer->Print(*vars, "if (!sent) {\n");

  printer->Indent();
  printer->Print(*vars, "NSError* error = nil;\n");
  printer->Print(*vars, "if (!sent) {\n");

  printer->Indent();
  printer->Print(*vars,
                 "error = [NSError errorWithDomain:@\"DotDashPayAPI.$ServiceName$.$Method$\" "
                 "code:-1 userInfo:@{@\"type\": @\"RequestNotAcknowledged\"}];\n");
  printer->Outdent();

  printer->Print(*vars, "}\n");
  printer->Print(*vars, "completionCallback(error, nil);\n");
  printer->Outdent();

  printer->Print(*vars, "} else {\n");

  printer->Indent();

  if (update_responses.size() > 0) {
    for (int i = 0; i < update_responses.size(); ++i) {
      printer->Print(*vars, "if ($UpdateResponseClass$callback) {\n");
      printer->Indent();
      (*vars)["UpdateResponse"] = update_responses[i];
      printer->Print(
          *vars, "[SignalManager on:@\"$UpdateResponse$\" performCallback:$UpdateResponseClass$callback];\n");
      printer->Outdent();
      printer->Print(*vars, "}\n");
    }
  }

  printer->Print(*vars, "[SignalManager on:@\"$CompletionResponse$\" performCallback:completionCallback];\n");
  printer->Outdent();

  printer->Print(*vars, "}\n");
  printer->Outdent();

  printer->Print(*vars, "}];\n");

}

string GetServiceImplementation(const google::protobuf::ServiceDescriptor* service,
                                const Parameters &params) {
  string output;
  {
    // Scope the output stream so it closes and finalizes output to the string.
    google::protobuf::io::StringOutputStream output_stream(&output);
    google::protobuf::io::Printer printer(&output_stream, '$');
    map<string, string> vars;

    vars["Service"] = "DDP" + service->name();
    printer.Print(vars, "@implementation $Service$\n");
    printer.Print(vars, "\n");

    for (int i = 0; i < service->method_count(); ++i) {
      PrintHeaderClientMethodInterfaces(&printer, service->method(i), &vars, false);
      printer.Indent();
      PrintServiceMethodImplementation(&printer, service->method(i), &vars);
      printer.Outdent();
      printer.Print("}\n\n");
    }

    printer.Print(vars, "@end\n");
  }
  return output;
}

string GetHeaderEpilogue(const google::protobuf::FileDescriptor *file,
                         const Parameters &params) {
  string output;
  {
    // Scope the output stream so it closes and finalizes output to the string.
    google::protobuf::io::StringOutputStream output_stream(&output);
    google::protobuf::io::Printer printer(&output_stream, '$');
  }
  return output;
}

string GetSourceIncludes(const google::protobuf::ServiceDescriptor* service, const Parameters &params) {
  string output;
  {
    // Scope the output stream so it closes and finalizes output to the string.
    google::protobuf::io::StringOutputStream output_stream(&output);
    google::protobuf::io::Printer printer(&output_stream, '$');
    map<string, string> vars;

    vars["HeaderFilename"] = "DDP" + service->name() + ".h";
    printer.Print(vars, "#import \"$HeaderFilename$\"\n");
    printer.Print(vars, "\n");
    printer.Print(vars, "#import \"Bridge.h\"\n");
    printer.Print(vars, "#import \"DotDashPayAPI.h\"\n");
    printer.Print(vars, "#import \"Logging.h\"\n");
    printer.Print(vars, "#import \"SerialProtocol.h\"\n");
    printer.Print(vars, "#import \"SignalManager.h\"\n\n");

    const set<string> classes = ddprpc_generator::GetUniqueResponses(service, true);
    for (set<string>::iterator it = classes.begin(); it != classes.end(); ++it) {
      vars["ClassName"] = *it;
      printer.Print(vars, "#import \"$ClassName$.pbobjc.h\"\n");
    }
    printer.Print(vars, "\n");
  }
  return output;
}

}  // namespace ddprpc_objc_generator
